added animations... nothing new
mhmarina/Gameheads-SAP-2024 pull request #44
Opened 2024-07-26 02:24 UTC by blursified

NO MERGE ISSUES?????

2024-07-27 07:18 UTC, mhmarina approved these changes

2024-07-27 07:21 UTC, mhmarina requested changes

2024-07-27 07:21 UTC, mhmarina commented on Gameheads-SAP-2024/Assets/Prefabs/GameObjects/Player.prefab
> +  pullForce: 5
Just want to double check if you meant to change these metrics since it wasn't mentioned in your PR.

2024-07-27 16:36 UTC, blursified reviewed
oh i didn't mean to change those my bad :')

2024-07-28 03:57 UTC, blursified commented
nope im redoing this for the 25th time

2024-07-28 03:57 UTC, closed without merging